import BirdSvg from "./BirdSvg.vue"
import CatSvg from "./CatSvg.vue"
import CloudLightning from "./CloudLightning.vue"
import CloudMoon from "./CloudMoon.vue"
import CloudSun from "./CloudSun.vue"
import DogSvg from "./DogSvg.vue"
import DropSvg from "./DropSvg.vue"
import FireSvg from "./FireSvg.vue"
import FireSimple from "./FireSimple.vue"
import FishSimple from "./FishSimple.vue"
import FlowerLotus from "./FlowerLotus.vue"
import PawPrint from "./PawPrint.vue"
import RainbowCloud from "./RainbowCloud.vue"
import SparkleSvg from "./SparkleSvg.vue"
import StarFour from "./StarFour.vue"
import SunDim from "./SunDim.vue"
import SunHorizon from "./SunHorizon.vue"
import ThermometerCold from "./ThermometerCold.vue"
import ThermometerHot from "./ThermometerHot.vue"
import ThermometerSimple from "./ThermometerSimple.vue"
import TreeEvergreen from "./TreeEvergreen.vue"
import UmbrellaSimple from "./UmbrellaSimple.vue"
import WavesSvg from "./WavesSvg.vue"
export {
  BirdSvg, CatSvg, CloudLightning, CloudMoon, CloudSun, DogSvg, DropSvg, FireSvg, FireSimple, FishSimple, FlowerLotus, PawPrint, RainbowCloud, SparkleSvg, StarFour, SunDim, SunHorizon, ThermometerCold, ThermometerHot, ThermometerSimple, TreeEvergreen, UmbrellaSimple, WavesSvg
}