import AndroidLogo from "./AndroidLogo.vue"
import AppleLogo from "./AppleLogo.vue"
import DiscordLogo from "./DiscordLogo.vue"
import DribbbleLogo from "./DribbbleLogo.vue"
import FacebookLogo from "./FacebookLogo.vue"
import FigmaLogo from "./FigmaLogo.vue"
import FramerLogo from "./FramerLogo.vue"
import GithubLogo from "./GithubLogo.vue"
import GitlabLogo from "./GitlabLogo.vue"
import GitlabLogoSimple from "./GitlabLogoSimple.vue"
import GoogleLogo from "./GoogleLogo.vue"
import GooglePlayLogo from "./GooglePlayLogo.vue"
import InstagramLogo from "./InstagramLogo.vue"
import LinkedinLogo from "./LinkedinLogo.vue"
import MediumLogo from "./MediumLogo.vue"
import MessengerLogo from "./MessengerLogo.vue"
import NyTimesLogo from "./NyTimesLogo.vue"
import PhosphorLogo from "./PhosphorLogo.vue"
import PinterestLogo from "./PinterestLogo.vue"
import RedditLogo from "./RedditLogo.vue"
import SketchLogo from "./SketchLogo.vue"
import SlackLogo from "./SlackLogo.vue"
import SnapchatLogo from "./SnapchatLogo.vue"
import SpotifyLogo from "./SpotifyLogo.vue"
import SquareLogo from "./SquareLogo.vue"
import StripeLogo from "./StripeLogo.vue"
import TelegramLogo from "./TelegramLogo.vue"
import TiktokLogo from "./TiktokLogo.vue"
import TwitchLogo from "./TwitchLogo.vue"
import TwitterLogo from "./TwitterLogo.vue"
import WhatsappLogo from "./WhatsappLogo.vue"
import WindowsLogo from "./WindowsLogo.vue"
import YoutubeLogo from "./YoutubeLogo.vue"
export {
  AndroidLogo, AppleLogo, DiscordLogo, DribbbleLogo, FacebookLogo, FigmaLogo, FramerLogo, GithubLogo, GitlabLogo, GitlabLogoSimple, GoogleLogo, GooglePlayLogo, InstagramLogo, LinkedinLogo, MediumLogo, MessengerLogo, NyTimesLogo, PhosphorLogo, PinterestLogo, RedditLogo, SketchLogo, SlackLogo, SnapchatLogo, SpotifyLogo, SquareLogo, StripeLogo, TelegramLogo, TiktokLogo, TwitchLogo, TwitterLogo, WhatsappLogo, WindowsLogo, YoutubeLogo
}