import BaseballSvg from "./BaseballSvg.vue"
import BasketballSvg from "./BasketballSvg.vue"
import ClubSvg from "./ClubSvg.vue"
import CrownSvg from "./CrownSvg.vue"
import CrownSimple from "./CrownSimple.vue"
import DiamondSvg from "./DiamondSvg.vue"
import DiceFive from "./DiceFive.vue"
import DiceFour from "./DiceFour.vue"
import DiceOne from "./DiceOne.vue"
import DiceSix from "./DiceSix.vue"
import DiceThree from "./DiceThree.vue"
import DiceTwo from "./DiceTwo.vue"
import FinnTheHuman from "./FinnTheHuman.vue"
import FootballSvg from "./FootballSvg.vue"
import GameController from "./GameController.vue"
import GhostSvg from "./GhostSvg.vue"
import HeartSvg from "./HeartSvg.vue"
import HeartStraight from "./HeartStraight.vue"
import HorseSvg from "./HorseSvg.vue"
import MedalSvg from "./MedalSvg.vue"
import PokerChip from "./PokerChip.vue"
import PuzzlePiece from "./PuzzlePiece.vue"
import SoccerBall from "./SoccerBall.vue"
import SpadeSvg from "./SpadeSvg.vue"
import StarHalf from "./StarHalf.vue"
import SwordSvg from "./SwordSvg.vue"
import TargetSvg from "./TargetSvg.vue"
import TennisBall from "./TennisBall.vue"
import TrophySvg from "./TrophySvg.vue"
import VolleyballSvg from "./VolleyballSvg.vue"
export {
  BaseballSvg, BasketballSvg, ClubSvg, CrownSvg, CrownSimple, DiamondSvg, DiceFive, DiceFour, DiceOne, DiceSix, DiceThree, DiceTwo, FinnTheHuman, FootballSvg, GameController, GhostSvg, HeartSvg, HeartStraight, HorseSvg, MedalSvg, PokerChip, PuzzlePiece, SoccerBall, SpadeSvg, StarHalf, SwordSvg, TargetSvg, TennisBall, TrophySvg, VolleyballSvg
}