import AlarmSvg from "./AlarmSvg.vue"
import CalendarSvg from "./CalendarSvg.vue"
import CalendarBlank from "./CalendarBlank.vue"
import CalendarCheck from "./CalendarCheck.vue"
import CalendarPlus from "./CalendarPlus.vue"
import CalendarX from "./CalendarX.vue"
import ClockSvg from "./ClockSvg.vue"
import ClockAfternoon from "./ClockAfternoon.vue"
import ClockClockwise from "./ClockClockwise.vue"
import ClockCounterClockwise from "./ClockCounterClockwise.vue"
import HourglassSvg from "./HourglassSvg.vue"
import HourglassHigh from "./HourglassHigh.vue"
import HourglassLow from "./HourglassLow.vue"
import HourglassMedium from "./HourglassMedium.vue"
import HourglassSimple from "./HourglassSimple.vue"
import HourglassSimpleHigh from "./HourglassSimpleHigh.vue"
import HourglassSimpleLow from "./HourglassSimpleLow.vue"
import HourglassSimpleMedium from "./HourglassSimpleMedium.vue"
import TimerSvg from "./TimerSvg.vue"
import WatchSvg from "./WatchSvg.vue"
export {
  AlarmSvg, CalendarSvg, CalendarBlank, CalendarCheck, CalendarPlus, CalendarX, ClockSvg, ClockAfternoon, ClockClockwise, ClockCounterClockwise, HourglassSvg, HourglassHigh, HourglassLow, HourglassMedium, HourglassSimple, HourglassSimpleHigh, HourglassSimpleLow, HourglassSimpleMedium, TimerSvg, WatchSvg
}