import CircleWavy from "./CircleWavy.vue"
import CircleWavyCheck from "./CircleWavyCheck.vue"
import CircleWavyQuestion from "./CircleWavyQuestion.vue"
import CircleWavyWarning from "./CircleWavyWarning.vue"
import Connect1Svg from "./Connect1Svg.vue"
import Connect2Svg from "./Connect2Svg.vue"
import FingerprintSimple from "./FingerprintSimple.vue"
import InfoSvg from "./InfoSvg.vue"
import LockKey from "./LockKey.vue"
import LockKeyOpen from "./LockKeyOpen.vue"
import LockLaminated from "./LockLaminated.vue"
import LockLaminatedOpen from "./LockLaminatedOpen.vue"
import LockSimple from "./LockSimple.vue"
import LockSimpleOpen from "./LockSimpleOpen.vue"
import ProhibitSvg from "./ProhibitSvg.vue"
import ProhibitInset from "./ProhibitInset.vue"
import QuestionSvg from "./QuestionSvg.vue"
import ShieldPlus from "./ShieldPlus.vue"
import ShieldSlash from "./ShieldSlash.vue"
import ShieldWarning from "./ShieldWarning.vue"
import WarningSvg from "./WarningSvg.vue"
import WarningCircle from "./WarningCircle.vue"
import WarningOctagon from "./WarningOctagon.vue"
import InputSvg from "./InputSvg.vue"
import OrderDelete from "./OrderDelete.vue"
import OrderCancel from "./OrderCancel.vue"
import OrderCheck from "./OrderCheck.vue"
import OrderCustomer from "./OrderCustomer.vue"
import OrderNew from "./OrderNew.vue"
import OrderProduct from "./OrderProduct.vue"
import OutputSvg from "./OutputSvg.vue"
export {
  CircleWavy, CircleWavyCheck, CircleWavyQuestion, CircleWavyWarning, Connect1Svg, Connect2Svg, FingerprintSimple, InfoSvg, LockKey, LockKeyOpen, LockLaminated, LockLaminatedOpen, LockSimple, LockSimpleOpen, ProhibitSvg, ProhibitInset, QuestionSvg, ShieldPlus, ShieldSlash, ShieldWarning, WarningSvg, WarningCircle, WarningOctagon, InputSvg, OrderDelete, OrderCancel, OrderCheck, OrderCustomer, OrderNew, OrderProduct, OutputSvg
}